Add completion_webhook params to assignment documentation
indeedassessments/api-documentation pull request #9
Opened 2018-08-16 21:20 UTC by robvitaro

Refer to https://github.com/indeedassessments/ia-web/pull/1785

2018-08-16 21:23 UTC, mightynimble approved these changes
👍

2018-08-16 21:24 UTC, juandazapata requested changes

2018-08-16 21:24 UTC, juandazapata commented on sections/assignments.md
> +- `completion_webhook_url` _(optional)_ - Creates a webhook in Indeed Assessments.
What's the HTTP verb that we use when sending the webhook? I think that's important to show. WDYT?

2018-08-17 13:06 UTC, robvitaro commented on sections/assignments.md
> +- `completion_webhook_url` _(optional)_ - Creates a webhook in Indeed Assessments.
@juandazapata, I updated the text at line 597

2018-08-31 12:05 UTC, juandazapata approved these changes

2018-08-31 12:05 UTC, merged